# Generated by Django 3.2.12 on 2023-10-28 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='会社名')),
                ('phone_number', models.CharField(max_length=255, verbose_name='電話番号')),
                ('pdf_file', models.FileField(upload_to='pdf_file', verbose_name='何かしらのPDFファイル')),
            ],
        ),
    ]
