# Generated by Django 3.2.12 on 2023-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='desired_contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='契約希望日'),
        ),
    ]
